### ISSUE TITLE
Minor data error

### ISSUE THREAD

**Issue by Lynnesbian** [zigtools/release-worker#1]
The 32-bit x86 build of zls 0.9.0 for Linux is incorrectly labelled as `x86.tar-linux` (as opposed to `x86-linux`).

![image](https://github.com/user-attachments/assets/4caa0ec1-9d99-494e-981d-d7202a9fc03f)

```
❯ curl -sL https://releases.zigtools.org/v1/zls/index.json | jq '."0.9.0"."x86.tar-linux"'
```
```json
{
  "tarball": "https://builds.zigtools.org/zls-linux-x86.tar-0.9.0.tar.xz",
  "shasum": "4596d0fcf236da331fa3afd9f282ac2492f22469f1b673465035b80850f4bd01",
  "size": "1187788"
}
```

There's no problem with the archive itself - the included `zls` binary seems to work fine - it's just a matter of labelling.

Apologies if this is not the proper place to open an issue - I understand that this issue does not pertain to the code contained in this repository.

**Comment by Techatrix** [comment]
Interesting find! I've renamed the build so it should be fixed now.
